--CREATE TABLE public.registro_acesso_end_point (
--  nome_end_point character varying,
--  qnt_acesso_end_point integer
--);
--
--INSERT INTO public.registro_acesso_end_point (nome_end_point, qnt_acesso_end_point) VALUES ('buscarPorNomePj', 0);
--INSERT INTO public.registro_acesso_end_point (nome_end_point, qnt_acesso_end_point) VALUES ('buscarPorCnpjPJ', 0);
--
--alter table public.registro_acesso_end_point add constraint nome_end_point_unique UNIQUE(nome_end_point);